# Generated by Django 2.2.6 on 2019-10-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseweight',
            old_name='exercise_reps',
            new_name='exerciseSetDetails',
        ),
    ]
