# Generated by Django 2.2.6 on 2019-12-26 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191107_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesetdetail',
            name='exercise_order',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
